version: 2
jobs:
  build:
    machine:
      timezone:
        Asia/Tokyo
      docker:
        - image: circleci/ruby:2.4.1
        - image: circleci/node:7.10.0
    steps:
      - checkout
    dependencies:
      override:
        - bundle install:
            timeout: 180
        - yarn
    database:
      pre:
        - mv config/database.yml.ci config/database.yml
      override:
        - bundle exec rake db:create db:schema:load     RAILS_ENV=test
        - bundle exec rake db:migrate RAILS_ENV=test
        - bundle exec rake db:seed RAILS_ENV=test
    test:
      override:
        - bundle exec rubocop
        - yarn run lint
        - bundle exec rspec spec/
